name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.0.6']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: 'rake :rubocop'
      run: bundle exec rake rubocop
    - name: 'rake :cookstyle'
      if: always()
      run: bundle exec rake cookstyle
    - name: 'rake :rspec'
      if: always()
      run: bundle exec rake rspec

